const cargosSemValue = [
  { value: '2', label: "ACUPUNTURISTA" },
  { value: '33', label: "ADVOGADO(A)" },
  { value: '4', label: "AGENTE ADMINISTRATIVO" },
  { value: '5', label: "AGENTE DE PORTARIA" },
  { value: '6', label: "ANALISTA ADMINISTRATIVO" },
  { value: '6', label: "ANALISTA AMBIENTAL" },
  { value: '6', label: "ANALISTA CONTABIL JUNIOR" },
  { value: '6', label: "ANALISTA CONTABIL SENIOR" },
  { value: '6', label: "ANALISTA CSL" },
  { value: '6', label: "ANALISTA DA QUALIDADE" },
  { value: '6', label: "ANALISTA DE ABASTECIMENTO" },
  { value: '6', label: "ANALISTA DE COMPRAS" },
  { value: '6', label: "ANALISTA DE COMUNICACAO" },
  { value: '6', label: "ANALISTA DE CONTABILIDADE" },
  { value: '6', label: "ANALISTA DE CONTRATACAO" },
  { value: '6', label: "ANALISTA DE CONTROLE INTERNO" },
  { value: '6', label: "ANALISTA DE DEPARTAMENTO PESSOAL JUNIOR" },
  { value: '6', label: "ANALISTA DE DEPARTAMENTO PESSOAL PLENO" },
  { value: '6', label: "ANALISTA DE DESENVOLVIMENTO " },
  { value: '6', label: "ANALISTA DE DESENVOLVIMENTO DE PARCEIROS" },
  { value: '6', label: "ANALISTA DE DESENVOLVIMENTO ORGANIZACIONAL JUNIOR" },
  { value: '6', label: "ANALISTA DE DESENVOLVIMENTO ORGANIZACIONAL PLENO" },
  { value: '6', label: "ANALISTA DE DESENVOLVIMENTO ORGANIZACIONAL SENIOR" },
  { value: '6', label: "ANALISTA DE ENGENHARIA" },
  { value: '6', label: "ANALISTA DE EXPEDIÇÃO" },
  { value: '6', label: "ANALISTA DE GESTAO DE FOLHA DE PAGAMENTO" },
  { value: '6', label: "ANALISTA DE GESTAO INTEGRADA" },
  { value: '6', label: "ANALISTA DE MEIO AMBIENTE" },
  { value: '6', label: "ANALISTA DE MONITORAMENTO E AVALIAÇÃO" },
  { value: '6', label: "ANALISTA DE OUVIDORIA" },
  { value: '6', label: "ANALISTA DE PRESTAÇÃO DE CONTAS PLENO" },
  { value: '6', label: "ANALISTA DE PRESTAÇÃO DE CONTAS SENIOR" },
  { value: '6', label: "ANALISTA DE PREVISAO" },
  { value: '6', label: "ANALISTA DE PROCESSOS" },
  { value: '6', label: "ANALISTA DE PROCESSOS FINANCEIROS" },
  { value: '6', label: "ANALISTA DE RECEBIMENTO E EXPEDIÇÃO" },
  { value: '6', label: "ANALISTA DE RECRUTAMENTO E SELEÇÃO " },
  { value: '6', label: "ANALISTA DE RELACOES TRABALHISTAS" },
  { value: '6', label: "ANALISTA DE TI" },
  { value: '6', label: "ANALISTA DE TREINAMENTO E DESENVOLVIMENTO" },
  { value: '6', label: "ANALISTA DEPARTAMENTO PESSOAL SENIOR" },
  { value: '6', label: "ANALISTA FINANCEIRO " },
  { value: '6', label: "ANALISTA FINANCEIRO JUNIOR" },
  { value: '6', label: "ANALISTA FINANCEIRO PLENO" },
  { value: '6', label: "ANALISTA JURIDICO" },
  { value: '6', label: "ANALISTA JURIDICO CSL" },
  { value: '6', label: "ANALISTA TECNICO (A) DE RESIDENCIA" },
  { value: '6', label: "ANALISTA TECNICO(A)" },
  { value: '6', label: "APRENDIZ  - ASSISTENTE ADMINISTRATIVO" },
  { value: '6', label: "ARQUITETO URBANISTA" },
  { value: '6', label: "ARTESÃ" },
  { value: '6', label: "ASSESSOR (A) ADMINISTRATIVO " },
  { value: '6', label: "ASSESSOR (A) DA DIRETORIA ADMINISTRATIVA" },
  { value: '6', label: "ASSESSOR (A) DE COMUNICAÇÃO" },
  { value: '6', label: "ASSESSOR (A) DE CONTABILIDADE" },
  { value: '6', label: "ASSESSOR (A) DE CONTRATO DE GESTAO" },
  { value: '6', label: "ASSESSOR (A) DE CONTROLE HOSPITALAR" },
  { value: '6', label: "ASSESSOR (A) DE DESENVOLVIMENTO" },
  { value: '6', label: "ASSESSOR (A) DE GOVERNANÇA" },
  { value: '6', label: "ASSESSOR (A) DE MONITORAMENTO E AVALIAÇAO " },
  { value: '6', label: "ASSESSOR (A) DE PLANEJAMENTO" },
  { value: '6', label: "ASSESSOR (A) DE PROJETOS" },
  { value: '6', label: "ASSESSOR DE ENGENHARIA AMBIENTAL" },
  { value: '6', label: "ASSESSOR TECNICO" },
  { value: '6', label: "ASSESSOR(A)" },
  { value: '6', label: "ASSESSOR(A) CLINICO" },
  { value: '6', label: "ASSESSOR(A) DE AUDITORIA HOSPITALAR" },
  { value: '6', label: "ASSESSOR(A) DE AUDITORIA INTERNA " },
  { value: '6', label: "ASSESSOR(A) DE CONTRATOS" },
  { value: '6', label: "ASSESSOR(A) DE CONTROLE INTERNO " },
  { value: '6', label: "ASSESSOR(A) DE ENGENHARIA" },
  { value: '6', label: "ASSESSOR(A) DE PLANEJAMENTO, GOVERNANÇA E INOVAÇÃO" },
  { value: '6', label: "ASSESSOR(A) DE RH" },
  { value: '6', label: "ASSESSOR(A) DO GABINETE" },
  { value: '6', label: "ASSESSOR(A) FINANCEIRO" },
  { value: '6', label: "ASSESSOR(A) INSTITUCIONAL DO GABINETE " },
  { value: '6', label: "ASSESSOR(A) JURIDICO" },
  { value: '6', label: "ASSESSOR(A) TECNICO(A) DE RH" },
  { value: '6', label: "ASSISTENTE ADMINISTRATIVO" },
  { value: '6', label: "ASSISTENTE ADMINISTRATIVO JUNIOR" },
  { value: '6', label: "ASSISTENTE ADMINISTRATIVO PLENO" },
  { value: '6', label: "ASSISTENTE ADMINISTRATIVO SENIOR" },
  { value: '6', label: "ASSISTENTE DE COMUNICACAO" },
  { value: '6', label: "ASSISTENTE DE CONTABILIDADE" },
  { value: '6', label: "ASSISTENTE DE COZINHA" },
  { value: '6', label: "ASSISTENTE DE DEPARTAMENTO PESSOAL JUNIOR" },
  { value: '6', label: "ASSISTENTE DE DESENVOLVIMENTO ORGANIZACIONAL SENIOR" },
  { value: '6', label: "ASSISTENTE DE GESTAO DE FOLHA DE PAGAMENTO" },
  { value: '6', label: "ASSISTENTE DE NECROPSIA/REMOVEDOR" },
  { value: '6', label: "ASSISTENTE DE PROCESSOS FINANCEIROS" },
  { value: '6', label: "ASSISTENTE DE TI" },
  { value: '6', label: "ASSISTENTE FINANCEIRO" },
  { value: '6', label: "ASSISTENTE SOCIAL" },
  { value: '6', label: "ATENDENTE DE CONSULTÓRIO" },
  { value: '6', label: "AUDITOR (A)" },
  { value: '6', label: "AUXILIAR ADMINISTRATIVO" },
  { value: '6', label: "AUXILIAR ADMINISTRATIVO JUNIOR" },
  { value: '6', label: "AUXILIAR DE ALMOXARIFADO" },
  { value: '6', label: "AUXILIAR DE COZINHA" },
  { value: '6', label: "AUXILIAR DE FARMÁCIA" },
  { value: '6', label: "AUXILIAR DE FATURAMENTO" },
  { value: '6', label: "AUXILIAR DE HOTELARIA" },
  { value: '6', label: "AUXILIAR DE LABORATORIO DE ANALISES CLINICAS" },
  { value: '6', label: "AUXILIAR DE MANUTENCAO " },
  { value: '6', label: "AUXILIAR DE NECROPSIA" },
  { value: '6', label: "AUXILIAR DE ROUPARIA" },
  { value: '6', label: "AUXILIAR DE SERVICOS GERAIS" },
  { value: '6', label: "AUXILIAR DE TI" },
  { value: '6', label: "AUXILIAR OPERACIONAL DE SERVIÇOS GERAIS" },
  { value: '6', label: "BIÓLOGO" },
  { value: '6', label: "BIOMEDICO" },
  { value: '6', label: "BIOQUIMICO" },
  { value: '6', label: "BIOQUIMICO/BIOMEDICO" },
  { value: '6', label: "BOMBEIRO CIVIL" },
  { value: '6', label: "CHEFE DE GABINETE" },
  { value: '6', label: "CHEFE(A) DO DEPARTAMENTO JURIDICO" },
  { value: '6', label: "CONSULTOR (A) DE ABASTECIMENTO" },
  { value: '6', label: "CONSULTOR (A) DE COMPRAS" },
  { value: '6', label: "CONSULTOR (A) DE CONTRATOS" },
  { value: '6', label: "CONSULTOR (A) DE CONTRATOS DE GESTAO" },
  { value: '6', label: "CONSULTOR (A) DE PROCESSOS" },
  { value: '6', label: "CONSULTOR(A) DE COMPRA HOSPITALAR" },
  { value: '6', label: "CONSULTOR(A) DE CONTROLE INTERNO FINANCEIRO" },
  { value: '6', label: "CONSULTOR(A) DE CONTABILIDADE" },
  { value: '6', label: "CONSULTOR(A) DE MONITORAMENTO E AVALIACAO" },
  { value: '6', label: "COORD. DA CAPTACAO DE DOADORES" },
  { value: '6', label: "COORD. DE ENSINO E PROJETOS EM SAUDE" },
  { value: '6', label: "COORDENACAO DE CERTIFICACAO" },
  { value: '6', label: "COORDENADOR (A)  DE ENFERMAGEM CENTRO CIRURGICO" },
  { value: '6', label: "COORDENADOR (A) DE ALMOXARIFADO" },
  { value: '6', label: "COORDENADOR (A) DE COMUNICAÇÃO E MARKETING" },
  { value: '6', label: "COORDENADOR (A) DE CONTRATOS DE GESTÃO " },
  { value: '6', label: "COORDENADOR (A) DE ENFERMAGEM DA QUALIDADE" },
  { value: '6', label: "COORDENADOR (A) DE ENFERMAGEM DE IMAGEM" },
  { value: '6', label: "COORDENADOR (A) DE ENFERMAGEM DE UTI/UI" },
  { value: '6', label: "COORDENADOR (A) DE ENFERMAGEM DO NEP" },
  { value: '6', label: "COORDENADOR (A) DE ENFERMAGEM NSP" },
  { value: '6', label: "COORDENADOR (A) DE ENFERMAGEM UTI PEDIATRICA" },
  { value: '6', label: "COORDENADOR (A) DE INFORMATICA" },
  { value: '6', label: "COORDENADOR (A) DE INFRAESTRUTURA" },
  { value: '6', label: "COORDENADOR (A) DE LABORATORIO" },
  { value: '6', label: "COORDENADOR (A) DE MONITORAMENTO E AVALIAÇÃO" },
  { value: '6', label: "COORDENADOR (A) DE PRODUÇÃO DE HEMOCOMPONENTES" },
  { value: '6', label: "COORDENADOR (A) DE RADIOLOGIA" },
  { value: '6', label: "COORDENADOR (A) DE SERVIÇOS ASSISTENCIAIS" },
  { value: '6', label: "COORDENADOR (A) DE TERAPIA OCUPACIONAL " },
  { value: '6', label: "COORDENADOR (A) DO NIR" },
  { value: '6', label: "COORDENADOR (A) DO SERVIÇO DE VERIFICAÇÃO DE ÓBITO" },
  { value: '6', label: "COORDENADOR (A) ENFERMAGEM CEM " },
  { value: '6', label: "COORDENADOR DA AGENCIA TRANSFUSIONAL " },
  { value: '6', label: "COORDENADOR DA CAPACITAÇÃO" },
  { value: '6', label: "COORDENADOR DA PRESTAÇÃO DE CONTAS" },
  { value: '6', label: "COORDENADOR DE AMBULATORIO" },
  { value: '6', label: "COORDENADOR DE ANALISE DE PROCESSO" },
  { value: '6', label: "COORDENADOR DE ATIVOS" },
  { value: '6', label: "COORDENADOR DE AUDITORIA HOSPITALAR" },
  { value: '6', label: "COORDENADOR DE AUDITORIA INTERNA" },
  { value: '6', label: "COORDENADOR DE CME" },
  { value: '6', label: "COORDENADOR DE COMPRAS" },
  { value: '6', label: "COORDENADOR DE CONTROLADORIA" },
  { value: '6', label: "COORDENADOR DE DESENVOLVIMENTO ORGANIZACIONAL" },
  { value: '6', label: "COORDENADOR DE DISTRIBUICAO DE HEMOCOMPONENTES" },
  { value: '6', label: "COORDENADOR DE FARMACIA" },
  { value: '6', label: "COORDENADOR DE FISIOTERAPIA UTI" },
  { value: '6', label: "COORDENADOR DE FOLLOW UP" },
  { value: '6', label: "COORDENADOR DE FROTA " },
  { value: '6', label: "COORDENADOR DE GESTAO DE FOLHA DE PAGAMENTO" },
  { value: '6', label: "COORDENADOR DE NUTRICAO" },
  { value: '6', label: "COORDENADOR DE PESSOAL" },
  { value: '6', label: "COORDENADOR DE REABILITAÇÃO" },
  { value: '6', label: "COORDENADOR DE RECRUTAMENTO E SELECAO" },
  { value: '6', label: "COORDENADOR DE SAUDE OCUPACIONAL" },
  { value: '6', label: "COORDENADOR DE SERVICO SOCIAL" },
  { value: '6', label: "COORDENADOR DE SISTEMAS" },
  { value: '6', label: "COORDENADOR DE SSMA" },
  { value: '6', label: "COORDENADOR DE TERCEIROS" },
  { value: '6', label: "COORDENADOR DO BANCO DE LEITE" },
  { value: '6', label: "COORDENADOR DO DEPARTAMENTO DE BIOLOGIA MOLECULAR" },
  { value: '6', label: "COORDENADOR MULTIDISCIPLINAR" },
  { value: '6', label: "COORDENADOR NUCLEO JURIDICO ADMINISTRATIVO" },
  { value: '6', label: "COORDENADOR(A) ADMINISTRATIVO" },
  { value: '6', label: "COORDENADOR(A) DE ABASTECIMENTO  " },
  { value: '6', label: "COORDENADOR(A) DE ATENDIMENTO" },
  { value: '6', label: "COORDENADOR(A) DE CENTROS ESPECIALIZADOS" },
  { value: '6', label: "COORDENADOR(A) DE CONTRATOS" },
  { value: '6', label: "COORDENADOR(A) DE ENFERMAGEM" },
  { value: '6', label: "COORDENADOR(A) DE ENFERMAGEM - CCIH" },
  { value: '6', label: "COORDENADOR(A) DE ENFERMAGEM - NIR" },
  { value: '6', label: "COORDENADOR(A) DE ENFERMAGEM DE MARCAÇÃO" },
  { value: '6', label: "COORDENADOR(A) DE ENFERMAGEM ESTOMOTERAPIA" },
  { value: '6', label: "COORDENADOR(A) DE ENFERMAGEM UTI ADULTO" },
  { value: '6', label: "COORDENADOR(A) DE FARMACIA" },
  { value: '6', label: "COORDENADOR(A) DE FATURAMENTO " },
  { value: '6', label: "COORDENADOR(A) DE FISIOTERAPIA" },
  { value: '6', label: "COORDENADOR(A) DE HOTELARIA" },
  { value: '6', label: "COORDENADOR(A) DE INSTALAÇÕES" },
  { value: '6', label: "COORDENADOR(A) DE LOGISTICA" },
  { value: '6', label: "COORDENADOR(A) DE MANUTENÇÃO" },
  { value: '6', label: "COORDENADOR(A) DE MARCAÇAO" },
  { value: '6', label: "COORDENADOR(A) DE NUTRICAO CLINICA" },
  { value: '6', label: "COORDENADOR(A) DE PROJETOS" },
  { value: '6', label: "COORDENADOR(A) DE RECURSOS HUMANOS" },
  { value: '6', label: "COORDENADOR(A) DE REGULAÇAO AMBULATORIAL" },
  { value: '6', label: "COORDENADOR(A) DE SEGURANÇA DA REGIONAL NORTE" },
  { value: '6', label: "COORDENADOR(A) DE TREINAMENTO E DESENVOLVIMENTO " },
  { value: '6', label: "COORDENADOR(A) DE UNID. DE ALIMENTACAO E NUTRICAO " },
  { value: '6', label: "COORDENADOR(A) DE UPAS" },
  { value: '6', label: "COORDENADOR(A) DO SESMT" },
  { value: '6', label: "COORDENADORA CENTRAL DE REGULACAO ONCOLOGICA" },
  { value: '6', label: "COPEIRO(A)" },
  { value: '6', label: "COZINHEIRO" },
  { value: '6', label: "DESENVOLVEDOR DE SISTEMAS" },
  { value: '6', label: "DESIGNER E EDITOR DE VIDEO" },
  { value: '6', label: "DESPENSEIRO" },
  { value: '6', label: "DIGITADOR" },
  { value: '6', label: "DIRETOR (A)" },
  { value: '6', label: "DIRETOR (A) GERAL" },
  { value: '6', label: "DIRETOR (A) GERAL ADJUNTO (A)" },
  { value: '6', label: "DIRETOR DO DEPARTAMENTO DE BIOLOGIA MOLECULAR" },
  { value: '6', label: "DIRETOR EXECUTIVO DE PLANEJ,GOVERNANÇA E INOVAÇÃO" },
  { value: '6', label: "DIRETOR TÉCNICO" },
  { value: '6', label: "DIRETOR TECNICO DA AGÊNCIA TRANSFUSIONAL" },
  { value: '6', label: "DIRETOR(A) ADMINISTRATIVO" },
  { value: '6', label: "DIRETOR(A) ADMINISTRATIVO ADJUNTO" },
  { value: '6', label: "DIRETOR(A) CLINICO" },
  { value: '6', label: "DIRETOR(A) DE PLANEJAMENTO E GOVERNANÇA" },
  { value: '6', label: "DIRETOR(A) DE RECURSOS HUMANOS" },
  { value: '6', label: "DIRETOR(A) DE REGULAÇÃO" },
  { value: '6', label: "DIRETOR(A) DO SETOR DE ENGENHARIA" },
  { value: '6', label: "DIRETOR(A) FINANCEIRO" },
  { value: '6', label: "EDUCADOR FISICO " },
  { value: '6', label: "ENCARREGADA DE SEGURANAÇA DO TRABALHO" },
  { value: '6', label: "ENCARREGADO (A) ADMINISTRATIVO" },
  { value: '6', label: "ENCARREGADO (A) DE FATURAMENTO" },
  { value: '6', label: "ENCARREGADO DE ALMOXARIFADO" },
  { value: '6', label: "ENCARREGADO DE ATENDIMENTO" },
  { value: '6', label: "ENCARREGADO DE COMPRAS" },
  { value: '6', label: "ENCARREGADO DE COMPRAS E ALMOXARIFADO" },
  { value: '6', label: "ENCARREGADO DE HOTELARIA" },
  { value: '6', label: "ENCARREGADO DE INFORMATICA" },
  { value: '6', label: "ENCARREGADO DE MANUTENÇÃO PREDIAL" },
  { value: '6', label: "ENCARREGADO DE OFICINA" },
  { value: '6', label: "ENCARREGADO DE PORTARIA " },
  { value: '6', label: "ENCARREGADO DE RECEPCAO" },
  { value: '6', label: "ENCARREGADO DE RECURSOS HUMANOS" },
  { value: '6', label: "ENCARREGADO DE ROUPARIA" },
  { value: '6', label: "ENCARREGADO DE SERVICOS GERAIS" },
  { value: '6', label: "ENCARREGADO DE TRANSPORTE" },
  { value: '6', label: "ENCARREGADO(A) DE ARQUIVO" },
  { value: '6', label: "ENCARREGADO(A) DE MAQUEIRO" },
  { value: '6', label: "ENCARREGADO(A) DE SISTEMAS" },
  { value: '6', label: "ENFERMEIRO (a) DO NEP" },
  { value: '6', label: "ENFERMEIRO (A) SOCORRISTA USA" },
  { value: '6', label: "ENFERMEIRO CCIH" },
  { value: '6', label: "ENFERMEIRO DE CENTRO CIRURGICO" },
  { value: '6', label: "ENFERMEIRO DE TERAPIA INTENSIVA" },
  { value: '6', label: "ENFERMEIRO DE TERAPIA INTENSIVA ADULTO" },
  { value: '6', label: "ENFERMEIRO DO TRABALHO" },
  { value: '6', label: "ENFERMEIRO NEFROLOGISTA" },
  { value: '6', label: "ENFERMEIRO NEONATOLOGISTA" },
  { value: '6', label: "ENFERMEIRO OBSTETRICO" },
  { value: '6', label: "ENFERMEIRO REGULADOR (A)" },
  { value: '6', label: "ENFERMEIRO SUPERVISOR (a)" },
  { value: '6', label: "ENFERMEIRO(A)" },
  { value: '6', label: "ENFERMEIRO(A) DE ESTOMOTERAPIA" },
  { value: '6', label: "ENFERMEIRO(A) DO TRABALHO" },
  { value: '6', label: "ENFERMEIRO(A) URGENCIA E EMERGENCIA" },
  { value: '6', label: "ENFERMEIRO(A) UTI ADULTO" },
  { value: '6', label: "ENFERMEIRO(A) UTI NEO" },
  { value: '6', label: "ENFERMEIRO(A) UTI PEDIATRICA" },
  { value: '6', label: "ENGENHEIRO CIVIL" },
  { value: '6', label: "ENGENHEIRO CLINICO" },
  { value: '6', label: "ENGENHEIRO DE PLANEJAMENTO" },
  { value: '6', label: "ENGENHEIRO DE PRODUCAO" },
  { value: '6', label: "ENGENHEIRO DE SEGURANCA DO TRABALHO" },
  { value: '6', label: "ENGENHEIRO ELETRICISTA" },
  { value: '6', label: "ENGENHEIRO MECANICO" },
  { value: '6', label: "ENGENHEIRO(A) DE MEIO AMBIENTE" },
  { value: '6', label: "ESPECIALISTA CLINICO" },
  { value: '6', label: "ESPECIALISTA DA QUALIDADE" },
  { value: '6', label: "ESPECIALISTA DE CERTIFICACAO " },
  { value: '6', label: "ESPECIALISTA DE GESTAO HOSPITALAR" },
  { value: '6', label: "ESPECIALISTA EM GESTAO DE PROCESSSOS" },
  { value: '6', label: "ESPECIALISTA EM SISTEMA DE INFORMACAO" },
  { value: '6', label: "ESPECIALISTA TECNICO (A)" },
  { value: '6', label: "EXECUTIVO (A) DE CONTABILIDADE" },
  { value: '6', label: "EXECUTIVO (A) DE GESTAO INTEGRADA" },
  { value: '6', label: "EXECUTIVO (A) FINANCEIRO" },
  { value: '6', label: "EXECUTIVO DE GESTAO DE PESSOAS" },
  { value: '6', label: "EXECUTIVO DE TI" },
  { value: '6', label: "EXECUTIVO(A) DE PROCESSOS FINANCEIROS" },
  { value: '6', label: "FARMACEUTICO" },
  { value: '6', label: "FARMACEUTICO INDUSTRIAL" },
  { value: '6', label: "FARMACEUTICO/BIOQUIMICO" },
  { value: '6', label: "FATURISTA" },
  { value: '6', label: "FISIOTERAPEUTA" },
  { value: '6', label: "FISIOTERAPEUTA ESP. EM TERAPIA INTENSIVA ADULTO" },
  { value: '6', label: "FISIOTERAPEUTA UTI" },
  { value: '6', label: "FISIOTERAPEUTA UTI PEDIATRICA" },
  { value: '6', label: "FISIOTERAPEUTA UTI PEDIATRICO E NEONATAL" },
  { value: '6', label: "FISIOTERAPEUTA UTI-ADULTO" },
  { value: '6', label: "FISIOTERAPEUTA UTI-NEO" },
  { value: '6', label: "FONOAUDIOLOGO" },
  { value: '6', label: "GERENTE ADMINISTRATIVO" },
  { value: '6', label: "GERENTE DA CAF" },
  { value: '6', label: "GERENTE DA QUALIDADE" },
  { value: '6', label: "GERENTE DA RESIDENCIA E ENSINO EM SAUDE" },
  { value: '6', label: "GERENTE DA SAUDE OCUPACIONAL" },
  { value: '6', label: "GERENTE DE AUDITORIA HOSPITALAR" },
  { value: '6', label: "GERENTE DE AUDITORIA INTERNA" },
  { value: '6', label: "GERENTE DE COMPRAS E CONTRATOS" },
  { value: '6', label: "GERENTE DE COMUNICACAO E MARKETING" },
  { value: '6', label: "GERENTE DE CONTABILIDADE" },
  { value: '6', label: "GERENTE DE DES. DE SISTEMAS" },
  { value: '6', label: "GERENTE DE DESENVOLVIMENTO" },
  { value: '6', label: "GERENTE DE ENFERMAGEM" },
  { value: '6', label: "GERENTE DE ENGENHARIA" },
  { value: '6', label: "GERENTE DE ENGENHARIA CLINICA" },
  { value: '6', label: "GERENTE DE ENGENHARIA E MANUTENCAO" },
  { value: '6', label: "GERENTE DE GESTÃO CORPORATIVA" },
  { value: '6', label: "GERENTE DE GESTÃO HOSPITALAR " },
  { value: '6', label: "GERENTE DE GESTAO INTEGRADA" },
  { value: '6', label: "GERENTE DE GOVERNANCA" },
  { value: '6', label: "GERENTE DE MEIO AMBIENTE" },
  { value: '6', label: "GERENTE DE MONITORAMENTO E AVALIAÇÃO" },
  { value: '6', label: "GERENTE DE OFICINA " },
  { value: '6', label: "GERENTE DE OUVIDORIA" },
  { value: '6', label: "GERENTE DE PARCERIAS" },
  { value: '6', label: "GERENTE DE POLÍTICA DE EDUCAÇÃO E  CONTROLE" },
  { value: '6', label: "GERENTE DE PRESTACAO DE CONTAS" },
  { value: '6', label: "GERENTE DE PROCESSOS CLINICOS " },
  { value: '6', label: "GERENTE DE PROCESSOS FINANCEIROS" },
  { value: '6', label: "GERENTE DE PROJETOS E CONTROLE" },
  { value: '6', label: "GERENTE DE RECURSOS HUMANOS" },
  { value: '6', label: "GERENTE DE RELACOES TRABALHISTAS" },
  { value: '6', label: "GERENTE DE SEGURANÇA DO TRABALHO" },
  { value: '6', label: "GERENTE DE SERVICO DE ASSISTENCIA FARMACEUTICA" },
  { value: '6', label: "GERENTE DE TECNOLOGIA DA INFORMACAO" },
  { value: '6', label: "GERENTE DO NUCLEO JURIDICO" },
  { value: '6', label: "GERENTE FINANCEIRO" },
  { value: '6', label: "GERENTE GERAL" },
  { value: '6', label: "GERENTE GERAL ADMINISTRATIVO" },
  { value: '6', label: "GERENTE GERAL DE ABASTECIMENTO" },
  { value: '6', label: "GERENTE GERAL DE ENFERMAGEM" },
  { value: '6', label: "GERENTE GERAL DE PLANEJAM, GOVERNANÇA E INOVAÇÃO" },
  { value: '6', label: "GERENTE GERAL DE SAUDE, SEGURANÇA E MEIO AMBIENTE" },
  { value: '6', label: "GERENTE NUCLEO JURIDICO ADMINISTRATIVO" },
  { value: '6', label: "GERENTE NUCLEO JURIDICO TRABALHISTA" },
  { value: '6', label: "GERENTE TECNICO" },
  { value: '6', label: "INSTRUMENTADOR CIRURGICO" },
  { value: '6', label: "INSTRUTOR DE TREINAMENTO" },
  { value: '6', label: "INTERPRETE DE LIBRAS" },
  { value: '6', label: "JORNALISTA" },
  { value: '6', label: "JOVEM APRENDIZ- ASSISTENTE ADMINISTRATIVO" },
  { value: '6', label: "LACTARISTA" },
  { value: '6', label: "MAQUEIRO" },
  { value: '6', label: "MEDICA DO TRABALHO" },
  { value: '6', label: "MEDICO (A) CLINICO (A)" },
  { value: '6', label: "Médico (a) Regulador " },
  { value: '6', label: "MEDICO CARDIOLOGISTA" },
  { value: '6', label: "MEDICO DO TRABALHO" },
  { value: '6', label: "MÉDICO ENDOCRINOLOGISTA" },
  { value: '6', label: "MEDICO ENDOCRINOLOGISTA E METABOLOGISTA" },
  { value: '6', label: "MEDICO GINECOLOGISTA E OBSTETRA" },
  { value: '6', label: "MEDICO HEMATOLOGISTA" },
  { value: '6', label: "MEDICO ORTOPEDISTA" },
  { value: '6', label: "MEDICO ORTOPEDISTA E TRAUMATOLOGISTA" },
  { value: '6', label: "MEDICO PEDIATRA" },
  { value: '6', label: "MEDICO PSIQUIATRA" },
  { value: '6', label: "MÉDICO VETERINÁRIO" },
  { value: '6', label: "MEMBRO DA COMISSÃO DE SINDICÂNCIA" },
  { value: '6', label: "MONITOR" },
  { value: '6', label: "MOTORISTA" },
  { value: '6', label: "MOTORISTA CATEGORIA D" },
  { value: '6', label: "MOTORISTA DA PRESIDENCIA" },
  { value: '6', label: "MOTORISTA DE AMBULANCIA" },
  { value: '6', label: "MOTORISTA DE CARRETA " },
  { value: '6', label: "MUSICISTA" },
  { value: '6', label: "MUSICOTERAPEUTA" },
  { value: '6', label: "NEUROPSICOLOGA" },
  { value: '6', label: "NUTRICIONISTA" },
  { value: '6', label: "ODONTOLOGISTA" },
  { value: '6', label: "ODONTOLOGO" },
  { value: '6', label: "OFICIAL DE MANUTENCAO" },
  { value: '6', label: "OPERADOR ANALISTA DA REGULAÇÃO AMBULATORIAL" },
  { value: '6', label: "OPERADOR ANALISTA DE CALL CENTER" },
  { value: '6', label: "OPERADOR DE REGULACAO" },
  { value: '6', label: "OUVIDOR" },
  { value: '6', label: "PODOLOGA" },
  { value: '6', label: "PORTEIRO" },
  { value: '6', label: "PREGOEIRO (A)" },
  { value: '6', label: "PREGOEIRO CSL" },
  { value: '6', label: "PRESIDENTE DA COMISSÃO DE SINDICÂNCIA" },
  { value: '6', label: "PRESIDENTE DA CSL" },
  { value: '6', label: "PRESIDENTE DA EMSERH" },
  { value: '6', label: "PROJETISTA" },
  { value: '6', label: "PSICOLOGO" },
  { value: '6', label: "PSICOPEDAGOGO" },
  { value: '6', label: "RECEPCIONISTA" },
  { value: '6', label: "SAPATEIRO" },
  { value: '6', label: "SECRETARIO(A)" },
  { value: '6', label: "SECRETÁRIO(A) DO CONSELHO " },
  { value: '6', label: "SUPERVISOR (A)  DE ENFERMAGEM OPME" },
  { value: '6', label: "SUPERVISOR (A) DE ENFERMAGEM" },
  { value: '6', label: "SUPERVISOR (A) DE ENFERMAGEM CCIH" },
  { value: '6', label: "SUPERVISOR (A) DE ENFERMAGEM DE UTI" },
  { value: '6', label: "SUPERVISOR (A) DE GESTÃO" },
  { value: '6', label: "SUPERVISOR (A) DE NUTRIÇÃO" },
  { value: '6', label: "SUPERVISOR (A) DE RECURSOS HUMANOS" },
  { value: '6', label: "SUPERVISOR (A) SERVICO SOCIAL" },
  { value: '6', label: "SUPERVISOR ADM DIARISTA DA PEDIATRIA" },
  { value: '6', label: "SUPERVISOR ADM DIARISTA DA UTI" },
  { value: '6', label: "SUPERVISOR ADMINISTRATIVO" },
  { value: '6', label: "SUPERVISOR ADMINISTRATIVO DE TRANSPORTE " },
  { value: '6', label: "SUPERVISOR CEMARC" },
  { value: '6', label: "SUPERVISOR DE ABASTECIMENTO" },
  { value: '6', label: "SUPERVISOR DE ALMOXARIFADO" },
  { value: '6', label: "SUPERVISOR DE AMBULATÓRIO " },
  { value: '6', label: "SUPERVISOR DE ARQUIVO" },
  { value: '6', label: "SUPERVISOR DE ATENDIMENTO" },
  { value: '6', label: "SUPERVISOR DE CCIH" },
  { value: '6', label: "SUPERVISOR DE DEPARTAMENTO PESSOAL" },
  { value: '6', label: "SUPERVISOR DE ENFERM DE INTERNAÇÃO" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM - CCIH/NHE" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM - NEP" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM - NIR" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM - URGENCIA" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM ALAS" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM C.C e CME" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM CENTRO CIRURGICO" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM DE AMBULATÓRIO" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM ENFERMARIA" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM QUALIDADE E VIEP" },
  { value: '6', label: "SUPERVISOR DE ENFERMAGEM UTI NEO" },
  { value: '6', label: "SUPERVISOR DE ENSINO" },
  { value: '6', label: "SUPERVISOR DE FISIOTERAPIA" },
  { value: '6', label: "SUPERVISOR DE FISIOTERAPIA UTI ADULTO" },
  { value: '6', label: "SUPERVISOR DE INFRAESTRUTURA" },
  { value: '6', label: "SUPERVISOR DE MANUTENÇÃO" },
  { value: '6', label: "SUPERVISOR DE NUTRIÇÃO" },
  { value: '6', label: "SUPERVISOR DE PORTARIA" },
  { value: '6', label: "SUPERVISOR DE PROTOCOLO" },
  { value: '6', label: "SUPERVISOR DE RADIOLOGIA" },
  { value: '6', label: "SUPERVISOR DE TERAPIA OCUPACIONAL" },
  { value: '6', label: "SUPERVISOR DE TI" },
  { value: '6', label: "SUPERVISOR DE TRANSPORTES" },
  { value: '6', label: "SUPERVISOR DO NIR" },
  { value: '6', label: "SUPERVISOR DO NUCLEO DE SEG. DO PACIENTE" },
  { value: '6', label: "SUPERVISOR EM INFORMATICA" },
  { value: '6', label: "SUPERVISOR FINANCEIRO" },
  { value: '6', label: "SUPERVISOR(A) ADMINISTRATIVO" },
  { value: '6', label: "SUPERVISOR(A) DA QUALIDADE" },
  { value: '6', label: "SUPERVISOR(A) DE AMBULATÓRIO SAE" },
  { value: '6', label: "SUPERVISOR(A) DE CONTRATOS" },
  { value: '6', label: "SUPERVISOR(A) DE ENFERMAGEM DA EPIDEMIOLOGIA " },
  { value: '6', label: "SUPERVISOR(A) DE ENFERMAGEM DE EMERGÊNCIA" },
  { value: '6', label: "SUPERVISOR(A) DE ENFERMAGEM NA CASA DA GESTANTE" },
  { value: '6', label: "SUPERVISOR(A) DE ENFERMAGEM NSP/NEP" },
  { value: '6', label: "SUPERVISOR(A) DE FARMACIA" },
  { value: '6', label: "SUPERVISOR(A) DE FATURAMENTO" },
  { value: '6', label: "SUPERVISOR(A) DE FATURAMENTO E CONTAS A PAGAR" },
  { value: '6', label: "SUPERVISOR(A) DE HOTELARIA" },
  { value: '6', label: "SUPERVISOR(A) TECNICO(A)" },
  { value: '6', label: "SUPERVISORA(A) DO REGISTRO HOSPITALAR DE CANCER" },
  { value: '6', label: "TAPECEIRO" },
  { value: '6', label: "TECNICO (A) DE ENFERMAGEM DO TRABALHO" },
  { value: '6', label: "TECNICO (A) DE IMOBILIZACAO ORTOPEDICA" },
  { value: '6', label: "TECNICO (A) ORCAMENTISTA" },
  { value: '6', label: "TECNICO DE EDIFICACOES" },
  { value: '6', label: "TECNICO DE ENFERMAGEM" },
  { value: '6', label: "TÉCNICO DE ENFERMAGEM DO TRABALHO " },
  { value: '6', label: "TECNICO DE ENFERMAGEM DO TRABALHO JUNIOR" },
  { value: '6', label: "TÉCNICO DE IMOBILIZAÇÃO" },
  { value: '6', label: "TECNICO DE LABORATORIO" },
  { value: '6', label: "TECNICO DE NECROPSIA" },
  { value: '6', label: "TECNICO DE SAUDE BUCAL " },
  { value: '6', label: "TECNICO ELETRICISTA" },
  { value: '6', label: "TECNICO EM ADMINISTRACAO" },
  { value: '6', label: "TECNICO EM GESSO" },
  { value: '6', label: "TECNICO EM HIGIENE BUCAL" },
  { value: '6', label: "TECNICO EM INFORMATICA" },
  { value: '6', label: "TÉCNICO EM LABORATÓRIO" },
  { value: '6', label: "TECNICO EM MANUTENÇÃO PREDIAL" },
  { value: '6', label: "TECNICO EM NUTRICAO" },
  { value: '6', label: "TÉCNICO EM RADIOLOGIA" },
  { value: '6', label: "TECNICO EM RADIOLOGIA E IMAGENOLOGIA" },
  { value: '6', label: "TECNICO EM SEGURANCA DO TRABALHO" },
  { value: '6', label: "TECNICO EM SEGURANCA DO TRABALHO JUNIOR" },
  { value: '6', label: "TECNICO EM TOMOGRAFIA" },
  { value: '6', label: "Tecnico Nivel Superior" },
  { value: '6', label: "TECNICO(A) DE ENFERMAGEM DE UTI" },
  { value: '6', label: "TELEFONISTA" },
  { value: '6', label: "TERAPEUTA OCUPACIONAL" },
  { value: '6', label: "TRADUTOR DE LIBRAS" },
  { value: '6', label: "COORDENADOR(A) ADMINISTRATIVO DIARISTA DE UTI" },
  { value: '6', label: "COORDENADOR (A) DE GESTAO INTEGRADA" },
  { value: '6', label: "COORDENADOR (A) MULTIPROFISSIONAL" },
  { value: '6', label: "GERENTE DE PLANEJAMENTO" },
  { value: '6', label: "DESIGNER DE UX/UI" },
  { value: '6', label: "ESPECIALISTA EM DOCUMENTAÇÃO DE SOFTWARE" },
]

export const cargos = cargosSemValue.map((cargo) => ({
  ...cargo,
  value: cargo.label,
}))


