const unidades = [
  { value: 786, label: "TODAS" },
    { value: 102, label: "AGENCIA TRANSFUSIONAL DE AÇAILANDIA" },
    { value: 560, label: "AGENCIA TRANSFUSIONAL DE ALTO PARNAIBA" },
    { value: 2, label: "AGENCIA TRANSFUSIONAL DE BACABAL" },
    { value: 3, label: "AGENCIA TRANSFUSIONAL DE BARRA DO CORDA" },
    { value: 24, label: "AGENCIA TRANSFUSIONAL DE CAROLINA" },
    { value: 4, label: "AGENCIA TRANSFUSIONAL DE CHAPADINHA" },
    { value: 25, label: "AGENCIA TRANSFUSIONAL DE COELHO NETO" },
    { value: 5, label: "AGENCIA TRANSFUSIONAL DE COLINAS" },
    { value: 27, label: "AGENCIA TRANSFUSIONAL DE COROATA" },
    { value: 28, label: "AGENCIA TRANSFUSIONAL DE CURURUPU" },
    { value: 29, label: "AGENCIA TRANSFUSIONAL DE GOV. NUNES FREIRE" },
    { value: 30, label: "AGENCIA TRANSFUSIONAL DE ITAPECURU" },
    { value: 31, label: "AGENCIA TRANSFUSIONAL DE PERITORO" },
    { value: 32, label: "AGENCIA TRANSFUSIONAL DE PORTO FRANCO" },
    { value: 33, label: "AGENCIA TRANSFUSIONAL DE PRESIDENTE DUTRA" },
    { value: 34, label: "AGENCIA TRANSFUSIONAL DE SANTA LUZIA" },
    { value: 35, label: "AGENCIA TRANSFUSIONAL DE SÃO JOÃO DOS PATOS" },
    { value: 36, label: "AGENCIA TRANSFUSIONAL DE TIMON" },
    { value: 37, label: "AGENCIA TRANSFUSIONAL DE VIANA" },
    { value: 38, label: "AGENCIA TRANSFUSIONAL DE ZE DOCA" },
    { value: 39, label: "CAF - FEME" },
    { value: 40, label: "CARRETA BARRETOS" },
    { value: 41, label: "CARRETA DA MULHER" },
    { value: 42, label: "CASA DA MULHER MARANHENSE DE IMPERATRIZ" },
    { value: 43, label: "CENTRO DA PESSOA IDOSA" },
    { value: 44, label: "CASA TEA 12+" },
    { value: 45, label: "CENTRAL DE REGULACAO - LEITOS" },
    { value: 46, label: "CENTRAL DE REGULACAO - AMBULATORIAL" },
    { value: 47, label: "CENTRAL DE REGULACAO - TRANSPORTE" },
    { value: 48, label: "CENTRO DE SAUDE GENESIO REGO" },
  { value: 49, label: "CENTRO DE TERAPIA RENAL SUBSTITUTIVA" },
  { value: 50, label: "CENTRO ESPECIALIZADO DE REAB. CIDADE OPERARIA" },
  { value: 51, label: "CENTRO ESPECIALIZADO DE REABILITACAO OLHO D'ÁGUA" },
  { value: 52, label: "FEME" },
  { value: 53, label: "FEME DE CAXIAS" },
  { value: 54, label: "FEME IMPERATRIZ" },
  { value: 55, label: "FEME PROGRAMA DO LEITE" },
  { value: 56, label: "FEME - UGAF" },
  { value: 57, label: "FESMA" },
  { value: 58, label: "HEMONUCLEO DE CAXIAS" },
  { value: 59, label: "HEMOMAR" },
  { value: 60, label: "HEMONUCLEO DE BACABAL" },
  { value: 61, label: "HEMONUCLEO DE BALSAS" },
  { value: 62, label: "HEMONUCLEO DE CODO" },
  { value: 63, label: "HEMONUCLEO DE IMPERATRIZ" },
  { value: 64, label: "HEMONUCLEO DE PEDREIRAS" },
  { value: 65, label: "HEMONUCLEO DE PINHEIRO" },
  { value: 66, label: "HEMONUCLEO DE SANTA INES" },
  { value: 67, label: "HOSPITAL ADELIA MATOS FONSECA" },
  { value: 68, label: "HOSPITAL REGIONAL ALARICO NUNES PACHECO - Timon" },
  { value: 69, label: "HOSPITAL AQUILES LISBOA" },
  { value: 70, label: "HOSPITAL DA ILHA" },
  { value: 71, label: "HOSPITAL GERAL DE ALTO ALEGRE" },
  { value: 72, label: "HOSPITAL REGIONAL DE BARRA DO CORDA" },
  { value: 73, label: "HOSPITAL DE BARREIRINHAS" },
  { value: 74, label: "HOSPITAL REGIONAL DE CARUTAPERA" },
  { value: 75, label: "HOSPITAL REGIONAL DE CHAPADINHA" },
  { value: 76, label: "HOSPITAL DE CUIDADOS INTENSIVOS - HCI" },
  { value: 77, label: "HOSPITAL GERAL DE GRAJAU" },
  { value: 78, label: "HOSPITAL REGIONAL DE LAGO DA PEDRA" },
  { value: 79, label: "HOSPITAL REGIONAL DE MORROS" },
  { value: 80, label: "HOSPITAL DE PAULINO NEVES" },
  { value: 81, label: "HOSPITAL DE PEDREIRAS" },
  { value: 82, label: "HOSPITAL GERAL DE PERITORO" },
  { value: 83, label: "HOSPITAL E MATERNIDADE ADERSON MARINHO - P. FRANCO" },
  { value: 84, label: "HOSPITAL PRESIDENTE DUTRA" },
  { value: 85, label: "HOSPITAL REGIONAL SANTA LUZIA DO PARUA" },
  { value: 86, label: "HOSPITAL REGIONAL DE TIMBIRAS" },
  { value: 87, label: "HOSPITAL MACRORREGIONAL DRA RUTH NOLETO" },
  { value: 88, label: "HOSPITAL GENESIO REGO" },
  { value: 89, label: "HOSPITAL GENESIO REGO - CENTRO DE TESTAGEM" },
  { value: 90, label: "HOSPITAL GENTIL FILHO - CAXIAS" },
  { value: 91, label: "HOSPITAL MACROREGIONAL DE CAXIAS" },
  { value: 92, label: "HOSPITAL MACROREGIONAL DE COROATA" },
  { value: 93, label: "HOSPITAL PRESIDENTE VARGAS" },
  { value: 94, label: "HOSPITAL VILA LUIZAO" },
  { value: 95, label: "LACEN" },
  { value: 96, label: "LACEN IMPERATRIZ" },
  { value: 97, label: "HOSPITAL MATERNO INFANTIL IMPERATRIZ" },
  { value: 98, label: "POLICLINICA CIDADE OPERARIA" },
  { value: 99, label: "POLICLINICA COHATRAC" },
  { value: 100, label: "POLICLINICA DO COROADINHO" },
  { value: 101, label: "POLICLINICA AÇAILANDIA" },
  { value: 102, label: "POLICLINICA BARRA DO CORDA" },
  { value: 103, label: "POLICLINICA CAXIAS" },
  { value: 104, label: "POLICLINICA DE CODÓ" },
  { value: 105, label: "POLICLINICA DE IMPERATRIZ" },
  { value: 106, label: "POLICLINICA DO CUJUPE" },
  { value: 107, label: "HOSPITAL GERAL DE MATOES DO NORTE" },
  { value: 108, label: "CENTRO ESPECIALIDADES MEDICAS PAM DIAMANTE" },
  { value: 109, label: "POLICLINICA VILA LUIZAO" },
  { value: 110, label: "POLICLINICA VINHAIS" },
  { value: 111, label: "RESIDENCIA MEDICA E MULTI - ANALISTAS TECNICOS" },
  { value: 113, label: "SHOPPING DA CRIANÇA" },
  { value: 114, label: "SOLAR DO OUTONO" },
  { value: 115, label: "SVO - SERV. VERIFICAÇÃO DE ÓBITOS - IMPERATRIZ" },
  { value: 116, label: "SVO - SERV. VERIFICAÇÃO DE ÓBITOS - SÃO LUÍS" },
  { value: 117, label: "SVO - SERV. VERIFICAÇÃO DE ÓBITOS - TIMON" },
  { value: 118, label: "TEA - CENTRO ESPECIALIZADO DE REAB. OLHO D'AGUA" },
  { value: 119, label: "UNIDADE DE CUIDADOS INTENSIVOS DE CODO" },
  { value: 120, label: "UPA ARACAGY" },
  { value: 121, label: "UPA CIDADE OPERARIA" },
  { value: 122, label: "UPA CODO" },
  { value: 123, label: "UPA COROATA" },
  { value: 124, label: "UPA DE IMPERATRIZ" },
  { value: 125, label: "UPA SAO JOAO DOS PATOS" },
  { value: 126, label: "UPA TIMON" },
  { value: 127, label: "UPA ITAQUI BACANGA" },
  { value: 128, label: "UPA PAÇO DO LUMIAR" },
  { value: 129, label: "UPA PARQUE VITORIA" },
  { value: 130, label: "UPA VINHAIS" },
  { value: 131, label: "CASA DA GESTANTE, BEBÊ E PUÉRPERA" },
  { value: 132, label: "CENTRO DE SAUDE GENESIO REGO" },
  { value: 133, label: "HOSPITAL GENESIO REGO (INTERNAÇÃO)" }
  ];


export const unidadesHospitalares = unidades.map((unidade) => ({
  ...unidade,
  value: unidade.label,
}))



